import { SectionDef } from '../types';

const SRC = 'SOURCE B · Doctors-Procedures.xlsx · Advance Aesthetic Solutions';

function retail(price: number): { audience: 'non_member'; amount: number; source_ref: string }[] {
  return [{ audience: 'non_member', amount: price, source_ref: SRC }];
}

const section: SectionDef = {
  slug: 'advance-aesthetic-solutions',
  name: 'Advance Aesthetic Solutions',
  description: 'Injectables, bio-remodeling, thread lifts, lipolysis, and metabolic therapies imported from Doctors-Procedures.xlsx (SOURCE B). Retail pricing; member discount TBD.',
  display_order: 23,
  is_bookable: false,
  services: [
    { name: 'E-Bella S Fat Dissolving Contouring (4+1 Sessions)', slug: 'aa-ebella-contouring-4plus1', category: 'injection', duration_minutes: 60, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826405', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(40000) },
    { name: 'E-Bella S Fat Dissolving Contouring', slug: 'aa-ebella-contouring', category: 'injection', duration_minutes: 20, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826396', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(40000) },
    { name: 'Luhilo Bio-Remodeling: Niacinamide & Glutathione UnderEye (3 Sessions)', slug: 'aa-luhilo-under-eye-3', category: 'injection', duration_minutes: 20, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826384', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(40000) },
    { name: 'Luhilo Bio-Remodeling: Niacinamide & Glutathione UnderEye', slug: 'aa-luhilo-under-eye', category: 'injection', duration_minutes: 20, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826376', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(15000) },
    { name: 'Signature Botox: Per Unit', slug: 'aa-botox-per-unit', category: 'injection', duration_minutes: 15, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826372', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(450) },
    { name: 'Signature Botox: Frontalis (Forehead)', slug: 'aa-botox-frontalis', category: 'injection', duration_minutes: 15, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826369', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(4950) },
    { name: 'Signature Botox: Periorbital (Crow\'s Feet)', slug: 'aa-botox-periorbital', category: 'injection', duration_minutes: 15, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826362', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(4950) },
    { name: 'Signature Botox: Jawline Slimming (Masseter)', slug: 'aa-botox-masseter', category: 'injection', duration_minutes: 15, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826357', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(12500) },
    { name: 'Signature Botox: Perioral (Lip Flip)', slug: 'aa-botox-lip-flip', category: 'injection', duration_minutes: 15, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826312', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(3500) },
    { name: 'Signature Botox: Hyperhidrosis Therapy', slug: 'aa-botox-hyperhidrosis', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826301', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(16500) },
    { name: 'Rejuran Healer (Rejuran H)', slug: 'aa-rejuran-healer', category: 'injection', duration_minutes: 60, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826294', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(25000) },
    { name: 'Rejuran HB (Hydro Booster)', slug: 'aa-rejuran-hb', category: 'injection', duration_minutes: 60, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826289', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(25000) },
    { name: 'Rejuran S (Rejuran Scar)', slug: 'aa-rejuran-scar', category: 'injection', duration_minutes: 60, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826278', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(25000) },
    { name: 'Rejuran I (Rejuran Eye)', slug: 'aa-rejuran-eye', category: 'injection', duration_minutes: 60, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826272', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(25000) },
    { name: 'PDRN Skin Healing Treatment', slug: 'aa-pdrn-healing', category: 'injection', duration_minutes: 60, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826269', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(10000) },
    { name: 'PDRN Bio-Repair Infusion + Exosome + DMAE', slug: 'aa-pdrn-bio-repair', category: 'injection', duration_minutes: 180, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826259', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(25000) },
    { name: 'Luhilo Bio-Remodeling: The Ultimate Lift', slug: 'aa-luhilo-ultimate-lift', category: 'injection', duration_minutes: 45, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826257', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(24999) },
    { name: 'Luhilo Bio-Remodeling: Underarm Whitening', slug: 'aa-luhilo-underarm-whitening', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826254', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(25000) },
    { name: 'Luhilo Bio-Remodeling: Axillary Rejuvenation w/ Niacinamide & Glutathione', slug: 'aa-luhilo-axillary', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826244', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(24999) },
    { name: 'Signature Lip Revitalization & Tint: Lip Rejuvenation', slug: 'aa-lip-revitalization', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826237', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(13900) },
    { name: 'Cellular Renewal Exosome Therapy: Face Rejuvenation', slug: 'aa-exosome-face', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826223', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(15900) },
    { name: 'Regenerative Scalp Exosome Therapy: Scalp & Hair Restoration', slug: 'aa-exosome-scalp', category: 'injection', duration_minutes: 15, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826214', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(23900) },
    { name: 'DMAE Youth-Firming Matrix: Firming / Anti-Aging', slug: 'aa-dmae-youth-firming', category: 'injection', duration_minutes: 150, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826193', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(8990) },
    { name: 'DMAE Luminous Complex: Antioxidant / Brightening', slug: 'aa-dmae-brightening', category: 'injection', duration_minutes: 150, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826188', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(8490) },
    { name: 'DMAE Hydro-Cellular Matrix: Hydration / Barrier Repair', slug: 'aa-dmae-hydration', category: 'injection', duration_minutes: 150, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826104', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(7990) },
    { name: 'Pimple Injections', slug: 'aa-pimple-injections', category: 'injection', duration_minutes: 60, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826093', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(1500) },
    { name: 'Face Thread Lift', slug: 'aa-face-thread-lift', category: 'injection', duration_minutes: 180, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826084', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(25000) },
    { name: 'Hiko Nose Thread', slug: 'aa-hiko-nose-thread', category: 'injection', duration_minutes: 180, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826082', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(25000) },
    { name: 'Additional Threads', slug: 'aa-additional-threads', category: 'injection', duration_minutes: 10, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826070', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(5000) },
    { name: 'Slim Point Premier Lipolysis: Comprehensive Area', slug: 'aa-slimpoint-comprehensive', category: 'injection', duration_minutes: 45, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826067', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(15990) },
    { name: 'Slim Point Premier Lipolysis: Standard Area', slug: 'aa-slimpoint-standard', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826063', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(12990) },
    { name: 'Slim Point Premier Lipolysis: Focal Area', slug: 'aa-slimpoint-focal', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826057', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(9990) },
    { name: 'Clinical Meso-Lipolysis: Standard Area', slug: 'aa-mesolipo-standard', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826026', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(9990) },
    { name: 'Clinical Meso-Lipolysis: Focal Area', slug: 'aa-mesolipo-focal', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826022', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(7490) },
    { name: 'Lemon Bio-Lipolysis: Body Focus', slug: 'aa-lemon-body', category: 'injection', duration_minutes: 30, treatment_type: 'Anti-Wrinkle Injections', external_id: '24826006', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(10990) },
    { name: 'Lemon Bio-Lipolysis: Facial Focus', slug: 'aa-lemon-facial', category: 'injection', duration_minutes: 15, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825986', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(8990) },
    { name: 'Metabolic Optimization (Tirzepatide) - 4 Week Program', slug: 'aa-tirzepatide-4week', category: 'injection', duration_minutes: 20, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825951', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(9990) },
    { name: 'Metabolic Optimization (Tirzepatide) - Single Session', slug: 'aa-tirzepatide-single', category: 'injection', duration_minutes: 20, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825938', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(9990) },
    { name: 'Metabolic Optimization (Compounded Tirzepatide)', slug: 'aa-compounded-tirzepatide', category: 'injection', duration_minutes: 20, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825930', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(4500) },
    { name: 'NAD+ Longevity Infusion: 1000 mg', slug: 'aa-nad-1000', category: 'injection', duration_minutes: 300, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825896', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(18990) },
    { name: 'NAD+ Longevity Infusion: 500 mg', slug: 'aa-nad-500', category: 'injection', duration_minutes: 240, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825888', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(10990) },
    { name: 'NAD+ Longevity Infusion: 300 mg', slug: 'aa-nad-300', category: 'injection', duration_minutes: 150, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825882', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(7990) },
    { name: 'NAD+ Longevity Infusion: 200 mg', slug: 'aa-nad-200', category: 'injection', duration_minutes: 90, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825868', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(6490) },
    { name: 'NAD+ Longevity Infusion: 100 mg', slug: 'aa-nad-100', category: 'injection', duration_minutes: 90, treatment_type: 'Anti-Wrinkle Injections', external_id: '24825858', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(4990) },
    { name: 'Advanced Dermal Scar Revision: Raised Scar Correction', slug: 'aa-scar-revision', category: 'injection', duration_minutes: 15, treatment_type: 'Skin Consultation', external_id: '24825843', online_booking: 'Enabled', available_for: 'Everyone', voucher_sales: 'Enabled', commissions: 'Enabled', prices: retail(3490) },
  ],
};

export default section;