import { SectionDef } from '../types';
import { waxRow } from '../helpers';

const section: SectionDef = {
  slug: 'hot-wax',
  name: 'Hot Wax',
  display_order: 22,
  services: [
    {
      name: 'Upper Lip',
      slug: 'upper-lip',
      category: 'other',
      duration_minutes: 10,
      prices: waxRow(200, 250, null),
    },
    {
      name: 'Eyebrow',
      slug: 'eyebrow',
      category: 'other',
      duration_minutes: 15,
      prices: waxRow(300, 400, null),
    },
    {
      name: 'Chin',
      slug: 'chin',
      category: 'other',
      duration_minutes: 10,
      prices: waxRow(200, 300, null),
    },
    {
      name: 'Half Arms',
      slug: 'half-arms',
      category: 'other',
      duration_minutes: 30,
      prices: waxRow(600, 750, 850),
    },
    {
      name: 'Full Arms',
      slug: 'full-arms',
      category: 'other',
      duration_minutes: 45,
      prices: waxRow(1000, 1250, 1500),
    },
    {
      name: 'Full Back',
      slug: 'full-back',
      category: 'other',
      duration_minutes: 60,
      prices: waxRow(1500, 1800, 2000),
    },
    {
      name: 'Full Legs',
      slug: 'full-legs',
      category: 'other',
      duration_minutes: 60,
      prices: waxRow(1500, 2000, 2500),
    },
    {
      name: 'Underarm',
      slug: 'underarm',
      category: 'other',
      duration_minutes: 20,
      prices: waxRow(400, 500, 600),
    },
    {
      name: 'Brazilian',
      slug: 'brazilian',
      category: 'other',
      duration_minutes: 45,
      prices: waxRow(1500, 2000, null),
    },
    {
      name: 'Bikini',
      slug: 'bikini',
      category: 'other',
      duration_minutes: 30,
      prices: waxRow(1000, 1250, null),
    },
    {
      name: 'Crutch Area',
      slug: 'crutch-area',
      category: 'other',
      duration_minutes: 20,
      prices: waxRow(500, 650, 750),
    },
    {
      name: 'Half Legs',
      slug: 'half-legs',
      category: 'other',
      duration_minutes: 45,
      prices: waxRow(800, 1000, 1200),
    },
    {
      name: 'Full Belly',
      slug: 'full-belly',
      category: 'other',
      duration_minutes: 30,
      prices: waxRow(500, 650, 750),
    },
    {
      name: 'Belly Line',
      slug: 'belly-line',
      category: 'other',
      duration_minutes: 15,
      prices: waxRow(200, 250, null),
    },
    {
      name: 'Buttocks',
      slug: 'buttocks',
      category: 'other',
      duration_minutes: 30,
      prices: waxRow(600, 750, 850),
    },
    {
      name: 'Nipple',
      slug: 'nipple',
      category: 'other',
      duration_minutes: 15,
      prices: waxRow(300, 400, 500),
    },
    {
      name: 'Face',
      slug: 'face',
      category: 'other',
      duration_minutes: 45,
      prices: waxRow(1500, 1800, 2000),
    },
    {
      name: 'Full Body',
      slug: 'full-body',
      category: 'other',
      duration_minutes: 120,
      prices: waxRow(8000, 10000, 12000),
    },
    {
      name: 'Full Body Half',
      slug: 'full-body-half',
      category: 'other',
      duration_minutes: 90,
      prices: waxRow(5000, 6000, 7000),
    },
    {
      name: 'Inner Thigh',
      slug: 'inner-thigh',
      category: 'other',
      duration_minutes: 20,
      prices: waxRow(500, 650, null),
    },
    {
      name: 'Jawline',
      slug: 'jawline',
      category: 'other',
      duration_minutes: 15,
      prices: waxRow(300, 400, 500),
    },
    {
      name: 'Underarm + Brazilian Wax',
      slug: 'underarm-brazilian-wax',
      category: 'other',
      duration_minutes: 45,
      inclusions: ['Underarm Wax', 'Brazilian Wax'],
      prices: waxRow(1800, 2300, null),
    },
    {
      name: 'Underarm + Bikini Wax',
      slug: 'underarm-bikini-wax',
      category: 'other',
      duration_minutes: 30,
      inclusions: ['Underarm Wax', 'Bikini Wax'],
      prices: waxRow(1300, 1650, null),
    },
    {
      name: 'Underarm + Crutch Area Wax',
      slug: 'underarm-crutch-area-wax',
      category: 'other',
      duration_minutes: 30,
      inclusions: ['Underarm Wax', 'Crutch Area Wax'],
      prices: waxRow(800, 1000, 1150),
    },
    {
      name: 'Underarm + Inner Thigh Wax',
      slug: 'underarm-inner-thigh-wax',
      category: 'other',
      duration_minutes: 30,
      inclusions: ['Underarm Wax', 'Inner Thigh Wax'],
      prices: waxRow(800, 1000, null),
    },
    {
      name: 'Underarm + Eyebrow Wax',
      slug: 'underarm-eyebrow-wax',
      category: 'other',
      duration_minutes: 20,
      inclusions: ['Underarm Wax', 'Eyebrow Wax'],
      prices: waxRow(600, 750, null),
    },
    {
      name: 'Underarm + Eyebrow + Upper Lip Wax',
      slug: 'underarm-eyebrow-upper-lip-wax',
      category: 'other',
      duration_minutes: 25,
      inclusions: ['Underarm Wax', 'Eyebrow Wax', 'Upper Lip Wax'],
      prices: waxRow(800, 1000, 1150),
    },
  ],
};

export default section;
